// Code generated by protoc-gen-go.
// source: post/post.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	post/post.proto

It has these top-level messages:
	Response
	Request
	Post
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Response struct {
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto1.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Post struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Created int32  `protobuf:"varint,2,opt,name=created" json:"created,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Article string `protobuf:"bytes,4,opt,name=article" json:"article,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto1.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*Response)(nil), "proto.Response")
	proto1.RegisterType((*Request)(nil), "proto.Request")
	proto1.RegisterType((*Post)(nil), "proto.Post")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Service service

type ServiceClient interface {
	List(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_ListClient, error)
	Add(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Response, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) List(ctx context.Context, in *Request, opts ...grpc.CallOption) (Service_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Service_serviceDesc.Streams[0], c.cc, "/proto.Service/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_ListClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type serviceListClient struct {
	grpc.ClientStream
}

func (x *serviceListClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) Add(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.Service/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Delete(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.Service/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	List(*Request, Service_ListServer) error
	Add(context.Context, *Post) (*Response, error)
	Delete(context.Context, *Post) (*Response, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).List(m, &serviceListServer{stream})
}

type Service_ListServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type serviceListServer struct {
	grpc.ServerStream
}

func (x *serviceListServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Add(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Delete(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Service_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Service_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Service_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("post/post.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x8f, 0x4d, 0x4a, 0xc6, 0x30,
	0x10, 0x86, 0xbf, 0xf4, 0xd7, 0x8e, 0x60, 0x61, 0x70, 0x11, 0xba, 0x2a, 0x01, 0x31, 0xab, 0x2a,
	0x7a, 0x02, 0xc1, 0xa5, 0x0b, 0x89, 0x17, 0xb0, 0x36, 0xb3, 0x08, 0x14, 0x53, 0x93, 0xd1, 0x0b,
	0x78, 0x71, 0x49, 0x7f, 0xc4, 0x9d, 0x9b, 0x84, 0xe7, 0xe5, 0x1d, 0xe6, 0x19, 0x68, 0x17, 0x1f,
	0xf9, 0x26, 0x3d, 0xc3, 0x12, 0x3c, 0x7b, 0x2c, 0xd7, 0x4f, 0x01, 0x9c, 0x19, 0x8a, 0x8b, 0x7f,
	0x8f, 0xa4, 0x1a, 0xa8, 0x0d, 0x7d, 0x7c, 0x52, 0x64, 0xf5, 0x0a, 0xc5, 0xb3, 0x8f, 0x8c, 0x17,
	0x90, 0x39, 0x2b, 0x45, 0x2f, 0x74, 0x6e, 0x32, 0x67, 0x51, 0x42, 0x3d, 0x05, 0x1a, 0x99, 0xac,
	0xcc, 0x7a, 0xa1, 0x4b, 0x73, 0x20, 0x5e, 0x42, 0xc9, 0x8e, 0x67, 0x92, 0x79, 0x2f, 0x74, 0x63,
	0x36, 0x48, 0xfd, 0x31, 0xb0, 0x9b, 0x66, 0x92, 0xc5, 0x9a, 0x1f, 0x78, 0xf7, 0x2d, 0xa0, 0x7e,
	0xa1, 0xf0, 0xe5, 0x26, 0xc2, 0x6b, 0x28, 0x9e, 0x5c, 0xda, 0xb6, 0xb9, 0x0d, 0xbb, 0x45, 0x77,
	0xbe, 0x73, 0x52, 0x51, 0xa7, 0x5b, 0x81, 0x57, 0x90, 0x3f, 0x58, 0x8b, 0x7f, 0xf3, 0xae, 0xfd,
	0x1d, 0xda, 0xcf, 0x38, 0xa1, 0x86, 0xea, 0x91, 0x66, 0x62, 0xfa, 0xaf, 0xf9, 0x56, 0xad, 0xc9,
	0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x19, 0x10, 0x73, 0x1f, 0x01, 0x00, 0x00,
}
